[pytest]
# 1. Default CLI arguments
addopts = --headed --html=reports/report.html --self-contained-html --alluredir=allure-results
testpaths = tests

# 3. File naming conventions
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 4. Custom Markers (prevents warnings)
markers =
    smoke: vital tests that must pass (login, register)
    regression: full suite tests
    contact: tests specifically for the contact page

# 5. Live Logs (shows what's happening in terminal)
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S